In [1]:
import pandas as pd

In [4]:
df = pd.read_parquet("../data/raw/molit/building_ledger/building_ledger_recap_all.parquet")
print(df.size, len(df))
print(df.columns)
df.head()

1675 25
Index(['rnum', 'platPlc', 'sigunguCd', 'bjdongCd', 'platGbCd', 'bun', 'ji',
       'mgmBldrgstPk', 'regstrGbCd', 'regstrGbCdNm', 'regstrKindCd',
       'regstrKindCdNm', 'newOldRegstrGbCd', 'newOldRegstrGbCdNm',
       'newPlatPlc', 'bldNm', 'splotNm', 'block', 'lot', 'bylotCnt',
       'naRoadCd', 'naBjdongCd', 'naUgrndCd', 'naMainBun', 'naSubBun',
       'platArea', 'archArea', 'bcRat', 'totArea', 'vlRatEstmTotArea', 'vlRat',
       'mainPurpsCd', 'mainPurpsCdNm', 'etcPurps', 'hhldCnt', 'fmlyCnt',
       'mainBldCnt', 'atchBldCnt', 'atchBldArea', 'totPkngCnt',
       'indrMechUtcnt', 'indrMechArea', 'oudrMechUtcnt', 'oudrMechArea',
       'indrAutoUtcnt', 'indrAutoArea', 'oudrAutoUtcnt', 'oudrAutoArea',
       'pmsDay', 'stcnsDay', 'useAprDay', 'pmsnoYear', 'pmsnoKikCd',
       'pmsnoKikCdNm', 'pmsnoGbCd', 'pmsnoGbCdNm', 'hoCnt', 'engrGrade',
       'engrRat', 'engrEpi', 'gnBldGrade', 'gnBldCert', 'itgBldGrade',
       'itgBldCert', 'crtnDay', 'aptSeq', 'ledger_api_type'],
      dtype='object')

,rnum,platPlc,sigunguCd,bjdongCd,platGbCd,bun,ji,mgmBldrgstPk,regstrGbCd,regstrGbCdNm,...,engrGrade,engrRat,engrEpi,gnBldGrade,gnBldCert,itgBldGrade,itgBldCert,crtnDay,aptSeq,ledger_api_type
0,1,서울특별시 종로구 평창동 45번지,11110,18300,0,0045,0000,10021486,2,집합,...,None,0,0,None,0,None,0,20220813,11110-146,recap
1,1,서울특별시 종로구 사직동 9번지,11110,11500,0,0009,0000,10021100180150,2,집합,...,None,0,0,None,0,None,0,20220813,11110-2203,recap
2,1,서울특별시 종로구 무악동 60번지,11110,18700,0,0060,0000,10021100182070,2,집합,...,None,0,0,None,0,None,0,20220813,11110-2212,recap
3,1,서울특별시 종로구 숭인동 2-1번지,11110,17500,0,0002,0001,10021100183699,2,집합,...,None,0,0,None,0,None,0,20240327,11110-2224,recap
4,1,서울특별시 종로구 숭인동 766번지,11110,17500,0,0766,0000,10021100185100,2,집합,...,None,0,0,None,0,None,0,20240206,11110-2234,recap

In [ ]:
df.totPkngCnt

0      208
1     1480
2     1108
3      525
4      349
5      375
6      212
7     1506
8      760
9      301
10      11
11     245
12      61
13       0
14     521
15       6
16      88
17       0
18     256
19     170
20       0
21    1365
22       8
23    2902
24     968
Name: totPkngCnt, dtype: object

In [3]:
df = pd.read_parquet("../data/raw/molit/building_ledger/building_ledger_all.parquet")
print(df.size, len(df))
print(df.columns)
df.head()

1164065 14735
Index(['rnum', 'platPlc', 'sigunguCd', 'bjdongCd', 'platGbCd', 'bun', 'ji',
       'mgmBldrgstPk', 'regstrGbCd', 'regstrGbCdNm', 'regstrKindCd',
       'regstrKindCdNm', 'newPlatPlc', 'bldNm', 'splotNm', 'block', 'lot',
       'bylotCnt', 'naRoadCd', 'naBjdongCd', 'naUgrndCd', 'naMainBun',
       'naSubBun', 'dongNm', 'mainAtchGbCd', 'mainAtchGbCdNm', 'platArea',
       'archArea', 'bcRat', 'totArea', 'vlRatEstmTotArea', 'vlRat', 'strctCd',
       'strctCdNm', 'etcStrct', 'mainPurpsCd', 'mainPurpsCdNm', 'etcPurps',
       'roofCd', 'roofCdNm', 'etcRoof', 'hhldCnt', 'fmlyCnt', 'heit',
       'grndFlrCnt', 'ugrndFlrCnt', 'rideUseElvtCnt', 'emgenUseElvtCnt',
       'atchBldCnt', 'atchBldArea', 'totDongTotArea', 'indrMechUtcnt',
       'indrMechArea', 'oudrMechUtcnt', 'oudrMechArea', 'indrAutoUtcnt',
       'indrAutoArea', 'oudrAutoUtcnt', 'oudrAutoArea', 'pmsDay', 'stcnsDay',
       'useAprDay', 'pmsnoYear', 'pmsnoKikCd', 'pmsnoKikCdNm', 'pmsnoGbCd',
       'pmsnoGbCdNm', 'hoCnt', 'engrGrade', 'engrRat', 'engrEpi', 'gnBldGrade',
       'gnBldCert', 'itgBldGrade', 'itgBldCert', 'crtnDay',
       'rserthqkDsgnApplyYn', 'rserthqkAblty', 'aptSeq'],
      dtype='object')

,rnum,platPlc,sigunguCd,bjdongCd,platGbCd,bun,ji,mgmBldrgstPk,regstrGbCd,regstrGbCdNm,...,engrRat,engrEpi,gnBldGrade,gnBldCert,itgBldGrade,itgBldCert,crtnDay,rserthqkDsgnApplyYn,rserthqkAblty,aptSeq
0,1,서울특별시 종로구 창신동 601-8번지,11110,17400,0,0601,0008,1002122300,2,집합,...,0,0,None,0,None,0,20220813,1,None,11110-100
1,1,서울특별시 종로구 평창동 46-1번지,11110,18300,0,0046,0001,1002112992,2,집합,...,0,0,None,0,None,0,20220813,1,None,11110-101
2,1,서울특별시 종로구 익선동 55번지,11110,13300,0,0055,0000,1002113267,2,집합,...,0,0,None,0,None,0,20220813,1,None,11110-102
3,1,서울특별시 종로구 숭인동 178-76번지,11110,17500,0,0178,0076,1002125361,2,집합,...,0,0,None,0,None,0,20220920,1,None,11110-105
4,1,서울특별시 종로구 내수동 95번지,11110,11800,0,0095,0000,1002114180,2,집합,...,0,0,None,0,None,0,20250411,1,None,11110-107

In [9]:
df.bylotCnt

0         0
1         2
2         0
3         0
4         0
         ..
14730     0
14731    10
14732     0
14733     0
14734     0
Name: bylotCnt, Length: 14735, dtype: object

In [6]:
df = pd.read_parquet("../data/processed/monthly_rent_summary.parquet")
print(df.size, len(df))
df.head()

6651832 604712

,ym,date,_lawd_cd,_region_name,rentType,거래건수,평균보증금,중앙값보증금,평균월세,중앙값월세,평균84환산보증금
0,201101,2011-01-01,11110,종로구,전세,1,33000.000000,33000.0,0.0,0.0,32666.0
1,201101,2011-01-01,11170,용산구,전세,1,20000.000000,20000.0,0.0,0.0,9702.0
2,201101,2011-01-01,11200,성동구,전세,1,43000.000000,43000.0,0.0,0.0,30838.0
3,201101,2011-01-01,11215,광진구,전세,3,16533.333333,21500.0,0.0,0.0,19786.333333
4,201101,2011-01-01,11230,동대문구,월세,1,5000.000000,5000.0,80.0,80.0,3658.0

In [7]:
df = pd.read_parquet("../data/processed/monthly_trade_summary.parquet")
print(df.size, len(df))
df.head()

161280 11520

,ym,_lawd_cd,_region_name,거래건수,평균거래금액,중앙값거래금액,평균84환산금액,중앙값84환산금액,절사평균거래금액,평균전용면적,평균건물연령,평균거래금액_60㎡이하,평균거래금액_60~85㎡,평균거래금액_85㎡초과
0,201001,11110,종로구,23,42036.521739,27900.0,43703.304348,42845.0,38454.736842,78.323913,11.043478,26022.222222,40663.333333,73334.000000
1,201001,11140,중구,35,47968.571429,42000.0,49536.0,53440.0,47584.482759,80.492000,8.628571,33010.000000,50365.000000,68300.000000
2,201001,11170,용산구,92,75650.000000,64250.0,69799.76087,70362.0,72097.972973,90.400913,17.021739,45256.000000,66045.000000,103974.324324
3,201001,11200,성동구,170,46390.294118,44000.0,50322.011765,49927.5,45527.426471,77.684747,11.388235,36220.303030,49143.414634,66638.636364
4,201001,11215,광진구,118,52052.542373,48950.0,53963.135593,55963.0,49220.833333,80.362119,13.872881,37048.837209,53583.870968,94376.923077

In [2]:
df = pd.read_parquet("../data/processed/apt_trade.parquet")
df.head()

,date,price,price_per_m2,price_per_py,price_std84,area,floor,construction_year,age,dong,apt_name,area_repr,dong_repr,apt_name_repr,aptSeq
0,2010-01-01,29850,580.29,1918.32,48744,51.440,5.0,1985,25.0,천호동,우성,51,천호동(11740),우성-구천면로(천호동),11740-173
1,2010-01-01,29000,483.64,1598.82,40626,59.962,4.0,2002,8.0,상동,라일락마을(신성미소지움),59,상동(41192),라일락마을(신성미소지움)-도약로(상동),41192-351
2,2010-01-01,18000,392.16,1296.39,32941,45.900,12.0,1988,22.0,상계동,상계주공9(고층),45,상계동(11350),상계주공9(고층)-노원로(상계동),11350-43
3,2010-01-01,49700,584.91,1933.60,49133,84.970,6.0,1993,17.0,평촌동,초원마을대원,84,평촌동(41173),초원마을대원-부림로(평촌동),41173-79
4,2010-01-01,36300,607.43,2008.04,51024,59.760,13.0,1999,11.0,가양동,가양강나루현대,59,가양동(11500),가양강나루현대-양천로(가양동),11500-143

In [3]:
df = pd.read_parquet("../data/processed/apt_rent.parquet")
df.head()

,date,deposit,deposit_per_m2,deposit_per_py,deposit_std84,monthly_rent,monthly_rent_per_m2,monthly_rent_per_py,area,floor,...,age,dong,apt_name,area_repr,dong_repr,apt_name_repr,aptSeq,contract_type,contract_term,use_rr_right
0,2011-01-01,3100,52.19,172.52,4384,0,0.00,0.00,59.40,10.0,...,14.0,광장동,상록타워아파트,59,광장동(11215),상록타워아파트-(광장동),11215-144,,,
1,2011-01-01,5000,43.55,143.97,3658,80,0.70,2.30,114.81,18.0,...,14.0,전농동,동아,114,전농동(11230),동아-(전농동),11230-8,,,
2,2011-01-01,4700,100.09,330.86,8407,11,0.23,0.77,46.96,7.0,...,1.0,소하동,광명신촌휴먼시아2단지,46,소하동(41210),광명신촌휴먼시아2단지-(소하동),41210-3300,,,
3,2011-01-01,1562,31.36,103.67,2634,11,0.22,0.73,49.81,15.0,...,9.0,신곡동,주공9단지,49,신곡동(41150),주공9단지-(신곡동),41150-147,,,
4,2011-01-01,1249,31.51,104.16,2647,7,0.18,0.58,39.64,9.0,...,9.0,신곡동,주공9단지,39,신곡동(41150),주공9단지-(신곡동),41150-147,,,

In [ ]:
df = pd.read_parquet("../data/raw/molit/apt_trade/11110_201501.parquet")
df.head()

,aptDong,aptNm,aptSeq,bonbun,bubun,buildYear,buyerGbn,cdealDay,cdealType,dealAmount,...,roadNmBonbun,roadNmBubun,roadNmCd,roadNmSeq,roadNmSggCd,roadNmbCd,sggCd,slerGbn,umdCd,umdNm
0,,창신쌍용1,11110-37,0702,0000,1992,,,,"34,000",...,00019,00000,4100065,01,11110,0,11110,,17400,창신동
1,,광화문스페이스본(101동~105동),11110-2203,0009,0000,2008,,,,"110,000",...,00004,00000,4100135,03,11110,0,11110,,11500,사직동
2,,흥인,11110-40,0627,0021,1997,,,,"17,800",...,00131,00004,4100453,01,11110,0,11110,,17400,창신동
3,,종로센트레빌,11110-2224,0002,0001,2008,,,,"39,000",...,00047,00000,4100065,02,11110,0,11110,,17500,숭인동
4,,광화문스페이스본(101동~105동),11110-2203,0009,0000,2008,,,,"73,000",...,00004,00000,4100135,03,11110,0,11110,,11500,사직동

In [ ]:
sorted(df.columns)

['aptDong',
 'aptNm',
 'aptSeq',
 'bonbun',
 'bubun',
 'buildYear',
 'buyerGbn',
 'cdealDay',
 'cdealType',
 'dealAmount',
 'dealDay',
 'dealMonth',
 'dealYear',
 'dealingGbn',
 'estateAgentSggNm',
 'excluUseAr',
 'floor',
 'jibun',
 'landCd',
 'landLeaseholdGbn',
 'rgstDate',
 'roadNm',
 'roadNmBonbun',
 'roadNmBubun',
 'roadNmCd',
 'roadNmSeq',
 'roadNmSggCd',
 'roadNmbCd',
 'sggCd',
 'slerGbn',
 'umdCd',
 'umdNm']

In [ ]:
df = pd.read_parquet("../data/raw/molit/building_ledger/building_ledger_all.parquet")
df.head()

,rnum,platPlc,sigunguCd,bjdongCd,platGbCd,bun,ji,mgmBldrgstPk,regstrGbCd,regstrGbCdNm,...,engrRat,engrEpi,gnBldGrade,gnBldCert,itgBldGrade,itgBldCert,crtnDay,rserthqkDsgnApplyYn,rserthqkAblty,aptSeq
0,1,서울특별시 종로구 창신동 601-8번지,11110,17400,0,0601,0008,1002122300,2,집합,...,0,0,None,0,None,0,20220813,1,None,11110-100
1,1,서울특별시 종로구 평창동 46-1번지,11110,18300,0,0046,0001,1002112992,2,집합,...,0,0,None,0,None,0,20220813,1,None,11110-101
2,1,서울특별시 종로구 익선동 55번지,11110,13300,0,0055,0000,1002113267,2,집합,...,0,0,None,0,None,0,20220813,1,None,11110-102
3,1,서울특별시 종로구 숭인동 178-76번지,11110,17500,0,0178,0076,1002125361,2,집합,...,0,0,None,0,None,0,20220920,1,None,11110-105
4,1,서울특별시 종로구 내수동 95번지,11110,11800,0,0095,0000,1002114180,2,집합,...,0,0,None,0,None,0,20250411,1,None,11110-107

In [ ]:
sorted(df.columns)

['aptSeq',
 'archArea',
 'atchBldArea',
 'atchBldCnt',
 'bcRat',
 'bjdongCd',
 'bldNm',
 'block',
 'bun',
 'bylotCnt',
 'crtnDay',
 'dongNm',
 'emgenUseElvtCnt',
 'engrEpi',
 'engrGrade',
 'engrRat',
 'etcPurps',
 'etcRoof',
 'etcStrct',
 'fmlyCnt',
 'gnBldCert',
 'gnBldGrade',
 'grndFlrCnt',
 'heit',
 'hhldCnt',
 'hoCnt',
 'indrAutoArea',
 'indrAutoUtcnt',
 'indrMechArea',
 'indrMechUtcnt',
 'itgBldCert',
 'itgBldGrade',
 'ji',
 'lot',
 'mainAtchGbCd',
 'mainAtchGbCdNm',
 'mainPurpsCd',
 'mainPurpsCdNm',
 'mgmBldrgstPk',
 'naBjdongCd',
 'naMainBun',
 'naRoadCd',
 'naSubBun',
 'naUgrndCd',
 'newPlatPlc',
 'oudrAutoArea',
 'oudrAutoUtcnt',
 'oudrMechArea',
 'oudrMechUtcnt',
 'platArea',
 'platGbCd',
 'platPlc',
 'pmsDay',
 'pmsnoGbCd',
 'pmsnoGbCdNm',
 'pmsnoKikCd',
 'pmsnoKikCdNm',
 'pmsnoYear',
 'regstrGbCd',
 'regstrGbCdNm',
 'regstrKindCd',
 'regstrKindCdNm',
 'rideUseElvtCnt',
 'rnum',
 'roofCd',
 'roofCdNm',
 'rserthqkAblty',
 'rserthqkDsgnApplyYn',
 'sigunguCd',
 'splotNm',
 'stcnsDay',
 'strctCd',
 'strctCdNm',
 'totArea',
 'totDongTotArea',
 'ugrndFlrCnt',
 'useAprDay',
 'vlRat',
 'vlRatEstmTotArea']

In [ ]:
df = pd.read_parquet("../data/processed/monthly_rent_summary.parquet")
df.head()

       ym _lawd_cd _region_name  거래건수         평균보증금       평균월세
0  202001    11110          종로구   156  35899.243590  44.198718
1  202001    11140           중구   253  36417.885375  31.411067
2  202001    11170          용산구   380  47536.486842  35.436842
3  202001    11200          성동구   787  41628.898348  33.678526
4  202001    11215          광진구   310  40437.738710  23.993548

In [ ]:
df._lawd_cd.unique()

array(['11110', '11140', '11170', '11200', '11215', '11230', '11260',
       '11290', '11305', '11320', '11350', '11380', '11410', '11440',
       '11470', '11500', '11530', '11545', '11560', '11590', '11620',
       '11650', '11680', '11710', '11740', '41111', '41113', '41115',
       '41117', '41131', '41133', '41135', '41171', '41173', '41192',
       '41194', '41210', '41220', '41271', '41273', '41281', '41285',
       '41287', '41410', '41430', '41461', '41463', '41465', '41591',
       '41593', '41595'], dtype=object)

In [ ]:
df._region_name.unique()

array(['종로구', '중구', '용산구', '성동구', '광진구', '동대문구', '중랑구', '성북구', '강북구',
       '도봉구', '노원구', '은평구', '서대문구', '마포구', '양천구', '강서구', '구로구', '금천구',
       '영등포구', '동작구', '관악구', '서초구', '강남구', '송파구', '강동구', '수원시 장안구',
       '수원시 권선구', '수원시 팔달구', '수원시 영통구', '성남시 수정구', '성남시 중원구', '성남시 분당구',
       '안양시 만안구', '안양시 동안구', '부천시 원미구', '부천시 소사구', '부천시 오정구', '광명시',
       '평택시', '안산시 상록구', '안산시 단원구', '고양시 덕양구', '고양시 일산동구', '고양시 일산서구',
       '군포시', '의왕시', '용인시 처인구', '용인시 기흥구', '용인시 수지구', '화성시 만세구',
       '화성시 효행구', '화성시 병점구', '화성시 동탄구'], dtype=object)

In [ ]:
df[df._region_name == "부천시 오정구"]

          ym _lawd_cd _region_name  거래건수         평균보증금       평균월세
36    202001    41196      부천시 오정구   243   7461.691358  16.814815
89    202002    41196      부천시 오정구   147  13368.809524  14.346939
142   202003    41196      부천시 오정구   117  10050.615385  15.666667
195   202004    41196      부천시 오정구   161  10542.888199  14.701863
248   202005    41196      부천시 오정구   167  12631.676647  13.341317
...      ...      ...          ...   ...           ...        ...
3561  202508    41196      부천시 오정구   108  14768.092593  28.009259
3613  202509    41196      부천시 오정구   125  15386.784000  25.328000
3665  202510    41196      부천시 오정구   102  14190.490196  31.960784
3717  202511    41196      부천시 오정구   113  14860.769912  33.840708
3769  202512    41196      부천시 오정구   160  11930.656250  34.618750

[72 rows x 6 columns]

In [ ]:
df = pd.read_parquet("../data/raw/molit/apt_trade/11110_202501.parquet")
df.head()

,aptDong,aptNm,aptSeq,bonbun,bubun,buildYear,buyerGbn,cdealDay,cdealType,dealAmount,...,roadNmBonbun,roadNmBubun,roadNmCd,roadNmSeq,roadNmSggCd,roadNmbCd,sggCd,slerGbn,umdCd,umdNm
0,102,인왕산아이파크,11110-2212,0060,0000,2008,개인,,,"115,000",...,00009,00000,4100482,01,11110,0,11110,개인,18700,무악동
1,105,현대,11110-90,0082,0000,2000,개인,,,"139,950",...,00246,00020,3000008,06,11110,0,11110,개인,18700,무악동
2,102,창신쌍용1,11110-37,0702,0000,1992,개인,,,"69,500",...,00019,00000,4100065,01,11110,0,11110,개인,17400,창신동
3,,엘리시아,11110-2261,0066,0001,2009,개인,,,"121,000",...,00142,00000,3100023,01,11110,0,11110,개인,18300,평창동
4,202,인왕산2차아이파크,11110-2417,0088,0000,2015,개인,,,"111,500",...,00034,00000,4100482,01,11110,0,11110,개인,18700,무악동

In [ ]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
aptDong,102,105,102,,202,이화에수풀,,,105,제101,...,1,109,,108,,103,로얄팰리스스위트,이화에수풀,,308
aptNm,인왕산아이파크,현대,창신쌍용1,엘리시아,인왕산2차아이파크,이화에수풀,인왕산아이파크,효성쥬얼리시티,광화문스페이스본(101동~105동),아남1,...,종로유케이201,현대,경희궁의아침2단지,현대,종로중흥S클래스,현대,로얄팰리스스위트,이화에수풀,경희궁의아침2단지,경희궁자이(3단지)
aptSeq,11110-2212,11110-90,11110-37,11110-2261,11110-2417,11110-2359,11110-2212,11110-2155,11110-2203,11110-25,...,11110-2334,11110-90,11110-115,11110-90,11110-2339,11110-90,11110-205,11110-2359,11110-115,11110-2446
bonbun,0060,0082,0702,0066,0088,0195,0060,0048,0009,0004,...,0201,0082,0071,0082,0202,0082,0085,0195,0071,0233
bubun,0000,0000,0000,0001,0000,0010,0000,0002,0000,0000,...,0011,0000,0000,0000,0003,0000,0000,0010,0000,0000
buildYear,2008,2000,1992,2009,2015,2014,2008,2006,2008,1995,...,2013,2000,2004,2000,2013,2000,2005,2014,2004,2017
buyerGbn,개인,개인,개인,개인,개인,법인,개인,개인,개인,개인,...,개인,개인,개인,개인,개인,개인,개인,개인,개인,개인
cdealDay,,,,,,,25.02.21,,,,...,,,,,,,,,,
cdealType,,,,,,,O,,,,...,,,,,,,,,,
dealAmount,"115,000","139,950","69,500","121,000","111,500","17,700","115,000","63,000","183,000","128,000",...,"9,300","139,900","255,000","124,900","12,300","87,970","31,000","19,000","180,000","181,500"
dealDay,18,25,24,18,19,14,18,23,31,10,...,14,11,11,7,2,7,6,4,4,3
dealMonth,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
dealYear,2025,2025,2025,2025,2025,2025,2025,2025,2025,2025,...,2025,2025,2025,2025,2025,2025,2025,2025,2025,2025
dealingGbn,중개거래,중개거래,중개거래,중개거래,중개거래,중개거래,중개거래,직거래,중개거래,중개거래,...,중개거래,중개거래,중개거래,중개거래,중개거래,중개거래,직거래,중개거래,중개거래,중개거래
estateAgentSggNm,서울 종로구,서울 종로구,서울 종로구,서울 종로구,서울 종로구,서울 성북구,서울 종로구,,서울 종로구,서울 종로구,...,서울 종로구,서울 종로구,서울 종로구,서울 종로구,서울 종로구,"서울 마포구, 서울 종로구",,서울 종로구,서울 종로구,서울 종로구
excluUseAr,84.858,114.9,79.87,213.07,84.2427,16.98,84.858,84.98,108.55,84.9,...,12.01,114.9,140.78,84.92,17.811,60,29.31,16.98,124.17,59.9425
floor,1,9,2,1,2,8,1,17,11,17,...,9,14,15,5,11,2,17,7,16,7
jibun,60,82,702,66-1,88,195-10,60,48-2,9,4,...,201-11,82,71,82,202-3,82,85,195-10,71,233
landCd,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
landLeaseholdGbn,N,N,N,N,N,N,N,N,N,N,...,N,N,N,N,N,N,N,N,N,N
rgstDate,25.03.28,25.05.29,25.02.26,,25.04.01,25.02.20,,25.02.06,25.03.27,25.07.04,...,25.02.24,25.02.26,25.03.27,25.04.02,25.02.14,25.04.01,25.01.07,25.02.05,25.01.31,25.03.31
roadNm,통일로18길,통일로,동망산길,평창문화로,통일로18길,대학로,통일로18길,종로,사직로8길,창경궁로,...,난계로29길,통일로,사직로8길,통일로,종로66길,통일로,율곡로2길,대학로,사직로8길,경교장길
roadNmBonbun,00009,00246,00019,00142,00034,00047,00009,00183,00004,00265,...,00033,00246,00024,00246,00028,00246,00007,00047,00024,00035
roadNmBubun,00000,00020,00000,00000,00000,00000,00000,00000,00000,00000,...,00004,00020,00000,00020,00000,00020,00000,00000,00000,00000
roadNmCd,4100482,3000008,4100065,3100023,4100482,3100002,4100482,3100013,4100135,3005008,...,4100030,3000008,4100135,3000008,4100372,3000008,4100234,3100002,4100135,4100002
roadNmSeq,01,06,01,01,01,05,01,09,03,07,...,01,06,05,06,01,06,01,05,05,01
roadNmSggCd,11110,11110,11110,11110,11110,11110,11110,11110,11110,11110,...,11110,11110,11110,11110,11110,11110,11110,11110,11110,11110
roadNmbCd,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,
sggCd,11110,11110,11110,11110,11110,11110,11110,11110,11110,11110,...,11110,11110,11110,11110,11110,11110,11110,11110,11110,11110
slerGbn,개인,개인,개인,개인,개인,개인,개인,개인,개인,개인,...,개인,개인,개인,개인,개인,개인,개인,개인,개인,개인
umdCd,18700,18700,17400,18300,18700,16600,18700,15700,11500,17100,...,17500,18700,11800,18700,17500,18700,12400,16600,11800,17700
umdNm,무악동,무악동,창신동,평창동,무악동,연건동,무악동,인의동,사직동,명륜2가,...,숭인동,무악동,내수동,무악동,숭인동,무악동,수송동,연건동,내수동,평동

In [ ]:
df

,aptDong,aptNm,aptSeq,bonbun,bubun,buildYear,buyerGbn,cdealDay,cdealType,dealAmount,...,roadNmBonbun,roadNmBubun,roadNmCd,roadNmSeq,roadNmSggCd,roadNmbCd,sggCd,slerGbn,umdCd,umdNm
0,,창신쌍용1,11110-37,0702,0000,1992,,,,"31,000",...,00019,00000,4100065,01,11110,0,11110,,17400,창신동
1,,삼성,11110-73,0596,0000,1998,,,,"53,000",...,00172,00000,3100023,01,11110,0,11110,,18300,평창동
2,,광화문스페이스본(106동),11110-2204,0009,0001,2008,,,,"162,000",...,00057,00000,4100010,01,11110,0,11110,,11500,사직동
3,,한빛,11110-27,0001,0030,1999,,,,"34,500",...,00008,00000,4100082,01,11110,0,11110,,17300,명륜3가
4,,창신쌍용1,11110-37,0702,0000,1992,,,,"68,500",...,00019,00000,4100065,01,11110,0,11110,,17400,창신동
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,,킹스매너,11110-118,0110,0015,2004,,,,"130,000",...,00005,00005,4100005,01,11110,0,11110,,11800,내수동
61,,종로청계힐스테이트,11110-2234,0766,0000,2009,,,,"100,000",...,00021,00000,4100204,01,11110,0,11110,,17500,숭인동
62,,롯데캐슬천지인,11110-152,0076,0000,2004,,,,"98,500",...,00347,00000,3100013,14,11110,0,11110,,17500,숭인동
63,,창신쌍용1,11110-37,0702,0000,1992,,,,"49,400",...,00019,00000,4100065,01,11110,0,11110,,17400,창신동
64,,창신쌍용2,11110-91,0703,0000,1993,,,,"54,500",...,00198,00000,4100020,02,11110,0,11110,,17400,창신동